name: Kubernetes Manifest Validation

on:
  pull_request:
    paths:
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"
  workflow_call:

jobs:
  k8s-validate:
    uses: actionsforge/actions/.github/workflows/k8s-manifest-validate.yml@main
    with:
      chart_dir: "."
      values_file: "values.yaml"
      kube_version: "1.33.0"
      enable_kubeconform: true
