name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Auto Tag Release"]
    types: [completed]

jobs:
  package:
    name: Package Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Chart
        run: helm lint .

      # - name: Package Chart
      #   run: |
      #     helm package .
      #     helm show chart *.tgz

      # - name: Upload Chart Artifacts
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: helm-chart
      #     path: "*.tgz"
      #     retention-days: 30
